import localFont from "next/font/local";
import "./globals.css";
import Nav from "./nav";
import Footer from "./footer";
import ThemeClient from "./ThemeClient";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeClient>
        <body className={`${geistSans.variable} ${geistMono.variable} `}>
          {/* theme provider */}

          <Nav />
          <main>
          {children}
          </main>
          <Footer />
          
        </body>
      </ThemeClient>
    </html>
  );
}
